In [1]:
import numpy as np

In [8]:
num_samples = 10
batch_size = 20
a = np.asarray([num_samples] * batch_size)

In [4]:
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

In [5]:
[num_samples] * batch_sizea

[10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10]

In [6]:
import torch as torch

In [9]:
batch_index = torch.LongTensor(range(batch_size))

In [10]:
batch_index

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [13]:
import pandas as pd
data = {
    'cpd1': ['A', 'B'],
    'cpd2': ['C', 'D'],
    'diff': [1.5, -2.3],
    'prop': [0.5, 0.7]
}

df = pd.DataFrame(data)
print(df['diff'], type(df['diff']))

0    1.5
1   -2.3
Name: diff, dtype: float64 <class 'pandas.core.series.Series'>


In [14]:
for value in df['diff']:
    print(value)

1.5
-2.3


In [15]:
df['diff'][0]

1.5

In [16]:
def find_interval(value, intervals):
    import re
    import math

    # 遍历每个区间字符串
    for interval in intervals:
        # 使用正则表达式提取边界
        bounds = re.findall(r'[\(\[]([^,]+),\s*([^,\)\]]+)[\)\]]', interval)
        if bounds:
            lower, upper = bounds[0]

            # 处理无穷大
            if lower == '-inf':
                lower = -math.inf
            else:
                lower = float(lower)

            if upper == 'inf':
                upper = math.inf
            else:
                upper = float(upper)

            # 检查数值是否属于当前区间
            if (lower < value <= upper) or (math.isclose(value, lower, rel_tol=1e-9) and '(' not in interval[0]):
                return interval
    return None

# 定义区间列表
intervals = [
    '(-inf, -10.5]', '(-10.5, -8.5]', '(-8.5, -6.5]', '(-6.5, -4.5]', '(-4.5, -2.5]',
    '(-2.5, -1.5]', '(-1.5, -1.0]', '(-1.0, -0.5]', '(-0.5, 0.0]', '(0.0, 0.5]',
    '(0.5, 1.0]', '(1.0, 1.5]', '(1.5, 2.5]', '(2.5, 4.5]', '(4.5, 6.5]', '(6.5, 8.5]',
    '(8.5, 10.5]', '(10.5, inf]'
]

# 测试函数
print(find_interval(-11, intervals))  # 输出应该是 '(-inf, -10.5]'
print(find_interval(-1, intervals))   # 输出应该是 '(-1.5, -1.0]'
print(find_interval(0.25, intervals)) # 输出应该是 '(0.0, 0.5]'

(-inf, -10.5]
(-1.5, -1.0]
(0.0, 0.5]


In [17]:
data = pd.read_csv('/home/yichao/zhilian/GenAICode/Data/MMPFinised/BindingDB_All_202407_1k/BindingDB_All_202407_1k_MMP.csv', sep=",")

In [18]:
data['value_type'][0]

'seq'

In [20]:
np.log10([10, 100])

array([1., 2.])

In [21]:
import csv

def save_top_rows(source_file_path, target_file_path, num_rows=10):
    with open(source_file_path, 'r', newline='') as source_file:
        reader = csv.reader(source_file)
        
        with open(target_file_path, 'w', newline='') as target_file:
            writer = csv.writer(target_file)
            
            for i, row in enumerate(reader):
                if i < num_rows:
                    writer.writerow(row)
                else:
                    break

# Example usage
source_path = '/home/yichao/zhilian/GenAICode/Data/MMPFinised/activity_Ki__BindingDB_All_202407/activity_Ki__BindingDB_All_202407_MMP.csv'
target_path = '/home/yichao/zhilian/GenAICode/Data/activity_Ki__BindingDB_All_202407_MMP_1k.csv'
save_top_rows(source_path, target_path, num_rows=1000)

In [6]:
from glob import glob
import os
import panda as pd

def check_file_size(file_path):
    # 获取文件大小，单位是字节
    file_size = os.path.getsize(file_path)
    
    # 将文件大小从字节转换为千字节
    file_size_kb = file_size / 1024 / 1024

    return file_size_kb
    

csv_files = glob(f"/home/yichao/zhilian/GenAICode/Data/MMPFinised_*/*/*_MMP.csv")
tar_list = []
for file in csv_files:
    file_size_mb = check_file_size(file)
    print(f'checking {file_size_mb}mb {file}')
    # 检查文件大小是否小于200KB
    if file_size_mb < 0.2:
        print("======小于!!!!!!!")
        tar_list.append(file)

checking 10845.242826461792mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_IC50__chembl34_IC50/activity_IC50__chembl34_IC50_MMP.csv
checking 161.4399881362915mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_IC50__BindingDB_All_202407/activity_IC50__BindingDB_All_202407_MMP.csv
checking 2027.7993211746216mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_Ki__chembl34_Ki/activity_Ki__chembl34_Ki_MMP.csv
checking 78.59825992584229mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_Kd__chembl34_Kd/activity_Kd__chembl34_Kd_MMP.csv
checking 98.47373008728027mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_Kd__BindingDB_All_202407/activity_Kd__BindingDB_All_202407_MMP.csv
checking 597.1856727600098mb /home/yichao/zhilian/GenAICode/Data/MMPFinised_activity/activity_EC50__BindingDB_All_202407/activity_EC50__BindingDB_All_202407_MMP.csv
checking 1043.0503826141357mb /home/yichao/zhilian/GenAICode/Data/MMPF

In [7]:
print(f'小于200kb的文件有 {len(tar_list)}')

小于200kb的文件有 145


In [11]:
import pandas as pd
temp = pd.read_csv("/home/yichao/zhilian/GenAICode/Data/MMPFinised_toxicity/toxicity_toxcast-NVS_GPCR_hAdoRA1__toxicity__toxcast-NVS_GPCR_hAdoRA1/toxicity_toxcast-NVS_GPCR_hAdoRA1__toxicity__toxcast-NVS_GPCR_hAdoRA1_MMP.csv")
temp.shape

(192, 16)

In [13]:
for file in tar_list:
    temp = pd.read_csv("/home/yichao/zhilian/GenAICode/Data/MMPFinised_toxicity/toxicity_toxcast-NVS_GPCR_hAdoRA1__toxicity__toxcast-NVS_GPCR_hAdoRA1/toxicity_toxcast-NVS_GPCR_hAdoRA1__toxicity__toxcast-NVS_GPCR_hAdoRA1_MMP.csv")
    print(f'===={temp.shape[0]}')
    if temp.shape[0] == 0:
        print(f'!!!!!!!==== emptry {file}')

====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
====192
